server:
  port: 8083

spring:
  application:
    name: clima-service

eureka:
  client:
    register-with-eureka: true
    fetch-register: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



